[package]
name = "rusty_container_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3"
tar= "0.4"
regex = "1"
flate2= "1"
nix = "0.26.2"