#!/bin/bash

set -e

defaultImage="hello-world"

image="${1:-$defaultImage}"
container=$(docker create "$image")

imagesBasePath="assets/images"
imagePath="${imagesBasePath}/${image}"

mkdir -p ${imagePath}
docker export "$container" -o "./${imagePath}/${image}.tar.gz"
docker rm "$container"

docker inspect -f '{{.Config.Cmd}}' "$image:latest" | tr -d '[]\n' > "./${imagePath}/${image}-cmd"

echo "Image content stored in ${imagePath}/${image}.tar.gz"